apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ytj-unionpay-notify
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - unionpay-notify.ytj.msjiay.com
      secretName: ytj-unionpay-notify-tls
  rules:
    - host: unionpay-notify.ytj.msjiay.com
      http:
        paths:
          - path:
            backend:
              serviceName: ytj-unionpay-notify
              servicePort: 80
