apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ytj-nonsense-fy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"
spec:
  tls:
    - hosts:
        - fy.nonsense.ytj.msjiay.com
      secretName: ytj-nonsense-fy-tls
  rules:
    - host: fy.nonsense.ytj.msjiay.com
      http:
        paths:
          - path: /
            backend:
              serviceName: ytj-app
              servicePort: 80
