apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ytj-device
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: device-test
#    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - device.ytj.msjiay.com
      secretName: ytj-device-tls
  rules:
    - host: device.ytj.msjiay.com
      http:
        paths:
          - path:
            backend:
              serviceName: ytj-device
              servicePort: 80
