apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ytj-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
    #nginx.ingress.kubernetes.io/auth-type: basic
    #nginx.ingress.kubernetes.io/auth-secret: web-admin
spec:
  tls:
    - hosts:
        - app.test.ytj.msjiay.com
      secretName: ytj-app-tls
  rules:
    - host: app.test.ytj.msjiay.com
      http:
        paths:
          - path:
            backend:
              serviceName: ytj-app
              servicePort: 80
