apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ytj-nonsense-ajkm
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
#    nginx.ingress.kubernetes.io/auth-type: basic
#    nginx.ingress.kubernetes.io/auth-secret: app-test
#    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - ajkm.nonsense.testing.ytj.msjiay.com
      secretName: ytj-nonsense-ajkm
  rules:
    - host: ajkm.nonsense.testing.ytj.msjiay.com
      http:
        paths:
          - path: /
            backend:
              serviceName: ytj-app
              servicePort: 80