apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socket
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
spec:
  tls:
    - hosts:
        - app.testing.stwakeng.com
      secretName: app-cert
  rules:
    - host: app.testing.stwakeng.com
      http:
        paths:
          - backend:
              service:
                name: socket
                port:
                  number: 80
            path: /ws
            pathType: Prefix