apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nsqadmin
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - nsqadmin.ytj.msjiay.com
    secretName: nsqadmin-tls
  rules:
  - host: nsqadmin.ytj.msjiay.com
    http:
      paths:
      - path:
        backend:
          serviceName: nsqadmin
          servicePort: 4171
