apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jaeger
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: ingress-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
spec:
  tls:
    - hosts:
        - jaeger.ytj.msjiay.com
      secretName: jaeger-tls
  rules:
    - host: jaeger.ytj.msjiay.com
      http:
        paths:
          - path: /
            backend:
              serviceName: jaeger-query
              servicePort: 16686
