apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: clm-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"
spec:
  tls:
    - hosts:
        - app.clm.msjiay.com
      secretName: clm-app-tls
  rules:
    - host: app.clm.msjiay.com
      http:
        paths:
          - path: /
            backend:
              serviceName: clm-app
              servicePort: 80
