version: '3.6'

services:
  etcd1:
    image: bitnami/etcd
    volumes:
      - ./data/etcd1:/var/etcd
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    environment:
      ETCD_NAME: etcd1
      ETCD_ROOT_PASSWORD: Pf*rm1D^V&hBDAKC
      ETCD_DATA_DIR: /var/etcd
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
    ports:
      - 6079:2379
      - 6080:2380
    networks:
      - mynet

  etcd2:
    image: bitnami/etcd
    volumes:
      - ./data/etcd2:/var/etcd
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    environment:
      ETCD_NAME: etcd2
      ETCD_ROOT_PASSWORD: Pf*rm1D^V&hBDAKC
      ETCD_DATA_DIR: /var/etcd
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd2:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd2:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
    ports:
      - 6179:2379
      - 6180:2380
    networks:
      - mynet

  etcd3:
    image: bitnami/etcd
    volumes:
      - ./data/etcd3:/var/etcd
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    environment:
      ETCD_NAME: etcd3
      ETCD_ROOT_PASSWORD: Pf*rm1D^V&hBDAKC
      ETCD_DATA_DIR: /var/etcd
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd3:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd3:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
    ports:
      - 6279:2379
      - 6280:2380
    networks:
      - mynet

networks:
  mynet:
