filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /app/logs/*.log

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "elasticsearch:5601"
  username: "elastic"
  password: "sxnywu1b6nxzetul"

#output.elasticsearch:
#  hosts: ["elasticsearch:9200"]
#  username: "elastic"
#  password: "sxnywu1b6nxzetul"