version: "3.5"
services:
  service:
    image: centos:7
    tty: true
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    networks:
      - network1

networks:
  network1:
    name: mynet
    external: true