version: '3.6'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.32
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - mynet

networks:
  mynet:
