version: '3.5'

services:
  rmqnamesrv:
    image: apache/rocketmq:4.9.4
    deploy:
      restart_policy:
        condition: on-failure
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./server/logs:/home/rocketmq/logs
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms256m -Xmx256m -Xmn256m"
    command: sh mqnamesrv
    networks:
      - mynet

  rmqbroker:
    image: apache/rocketmq:4.9.4
    deploy:
      restart_policy:
        condition: on-failure
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./broker/logs:/home/rocketmq/logs
      - ./broker/store:/home/rocketmq/store
      - ./broker.conf:/home/rocketmq/rocketmq-4.9.4/conf/broker.conf
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -server -Xms256m -Xmx256m -Xmn256m"
    command: [ "sh","mqbroker","-c","/home/rocketmq/rocketmq-4.9.4/conf/broker.conf","-n","rmqnamesrv:9876","autoCreateTopicEnable=true" ]
    depends_on:
      - rmqnamesrv
    networks:
      - mynet

  rmqconsole:
    image: apacherocketmq/rocketmq-dashboard:latest
    deploy:
      restart_policy:
        condition: on-failure
    container_name: rmqconsole
    ports:
      - 8180:8080
    volumes:
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    networks:
      - mynet

networks:
  mynet: