version: '3.6'
services:
  consul:
    image: consul
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    command:
      consul agent -dev -ui -client 0.0.0.0
    #      consul agent -server -bootstrap -ui -client 0.0.0.0 -bind '{{ GetInterfaceIP "eth0" }}' -data-dir /tmp/consul -datacenter dc01 -node web01
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    networks:
      - mynet

networks:
  mynet:

