version: '3.6'
services:
  consul-1:
    image: consul
    volumes:
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    command:
      consul agent -server -bootstrap -ui -client 0.0.0.0 -advertise 192.168.1.101 -data-dir /tmp/consul -datacenter dc01 -node web01
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    networks:
      - mynet

networks:
  mynet: