version: "3.5"
services:
  nginx:
    image: nginx
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - network1

networks:
  network1:
    name: mynet
    external: true