version: '3.3'
services:
  elasticsearch:
    image: elastic/elasticsearch:7.17.2
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: sxnywu1b6nxzetul
    networks:
      - mynet

  kibana:
    image: elastic/kibana:7.17.2
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    ports:
      - "5601:5601"
    networks:
      - mynet

  filebaet:
    image: registry.cn-hangzhou.aliyuncs.com/ysny/filebeat:7.17.2
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    command:
      - "-e"
      - "--strict.perms=false"
    networks:
      - mynet

networks:
  mynet:
    driver: overlay
