version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: sxnywu1b6nxzetul
    networks:
      - mynet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    ports:
      - "5601:5601"
    networks:
      - mynet

  filebaet:
    image: docker.elastic.co/beats/filebeat:7.4.2
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/module/springboot:/usr/share/filebeat/module/springboot
      - ./filebeat/modules.d/springboot.yml:/usr/share/filebeat/modules.d/springboot.yml
      - E:\development\java\spring-projects\bwton-marketing\logs:/app/logs
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    networks:
      - mynet

networks:
  mynet:
    driver: overlay
