version: '3.6'
services:
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 8000:8000
      - 9000:9000
    networks:
      - mynet

networks:
  mynet: