version: "3.1"
services:
  db:
    image: mysql
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./data:/mysqlData
      - ./mysql-files:/var/lib/mysql-files
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    command: >
      bash -c "
      chmod 644 /etc/mysql/my.cnf
      && /entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password
      "
    environment:
      MYSQL_ROOT_PASSWORD: mYL5VRClXYGCX4Hf
    ports:
      - 3306:3306
    networks:
      - mynet
networks:
  mynet: