version: "3.1"
services:
  db:   
    image: mysql
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./data:/mysqlData
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    command: 
      --default-authentication-plugin=mysql_native_password
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: mYL5VRClXYGCX4Hf
    ports:
      - 3306:3306
    networks:
      - mynet
networks:
  mynet: