web:
  image: gitlab/gitlab-ce:14.4.2-ce.0
  restart: always
  hostname: 'gitlab.msjiay.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.msjiay.com'
  ports:
    - '6080:80'
    - '6443:443'
    - '6022:22'
  volumes:
    - '/mnt/gitlab/config:/etc/gitlab'
    - '/mnt/gitlab/logs:/var/log/gitlab'
    - '/mnt/gitlab/data:/var/opt/gitlab'