version: "3.1"
services:
  db:   
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
      - ./data:/postgresData
    environment:
      POSTGRES_PASSWORD: Fever!@#456
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      PGDATA: /postgresData
    ports:
      - 5432:5432
    networks:
      - testnet

networks:
  testnet: