version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    command: /nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161
    networks:
      - mynet

  nsqd:
    image: nsqio/nsq
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
      - ./data:/data
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --data-path=/data -broadcast-address=nsqd
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151
    networks:
      - mynet

  nsqadmin:
    image: nsqio/nsq
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171
    networks:
      - mynet

networks:
  mynet: