version: '3.1'

services:
  mongo:
    image: mongo
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: w9vgs4mjsd0pmk40
    networks:
      - mynet

  mongo-express:
    image: mongo-express
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: w9vgs4mjsd0pmk40
    networks:
      - mynet

networks:
  mynet:
