version: "3.1"
services:
  db:
    image: redis
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/redisData
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    command:
      redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - mynet

networks:
  mynet: