version: "3.1"
services:
  db:   
    image: redis
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/redisData
      - ../etc/localtime:/etc/localtime:ro
      - ../etc/timezone:/etc/timezone:ro
    command: 
      redis-server /etc/redis/redis.conf
    deploy:
      replicas: 1      
      restart_policy:
        condition: on-failure
    ports:
      - 6379:6379
    networks:
      - mynet
networks:
  mynet: